/**
 * 0 ~ 999
 */
export const COMMON_ERROR_CODE = {
  SERVER_ERROR: 'SERVER_ERROR',
  INVALID_REQUEST_PARAMETER: 'INVALID_REQUEST_PARAMETER',
  API_NOT_FOUND: 'API_NOT_FOUND',
  INVALID_TOKEN: 'INVALID_TOKEN',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  MISSING_UPDATE_FIELD: 'MISSING_UPDATE_FIELD',
  INVALID_JSON_FORMAT: 'INVALID_JSON_FORMAT',
} as const;
