export const USER_CONNECTION_ERROR_CODE = {
  REQUESTER_ALREADY_HAVE_CONNECTION: 'REQUESTER_ALREADY_HAVE_CONNECTION',
  REQUESTER_ALREADY_SENT_PENDING_CONNECTION:
    'REQUESTER_ALREADY_SENT_PENDING_CONNECTION',
  REQUESTED_USER_ALREADY_HAVE_CONNECTION:
    'REQUESTED_USER_ALREADY_HAVE_CONNECTION',
  CANNOT_CREATE_CONNECTION_TARGET_EMAIL_NOT_VERIFIED:
    'CANNOT_CREATE_CONNECTION_TARGET_EMAIL_NOT_VERIFIED',
  CANNOT_CREATE_CONNECTION_MYSELF: 'CANNOT_CREATE_CONNECTION_MYSELF',
  CAN_ONLY_UPDATE_PENDING_CONNECTION: 'CAN_ONLY_UPDATE_PENDING_CONNECTION',
  CAN_ONLY_ACCEPT_CONNECTION_REQUEST_THAT_COME_TO_YOU:
    'CAN_ONLY_ACCEPT_CONNECTION_REQUEST_THAT_COME_TO_YOU',
  CAN_ONLY_REJECT_CONNECTION_REQUEST_THAT_COME_TO_YOU:
    'CAN_ONLY_REJECT_CONNECTION_REQUEST_THAT_COME_TO_YOU',
  CAN_ONLY_CANCEL_CONNECTION_REQUEST_THAT_YOU_SENT:
    'CAN_ONLY_CANCEL_CONNECTION_REQUEST_THAT_YOU_SENT',
  YOU_DO_NOT_HAVE_AN_ACCEPTED_CONNECTION:
    'YOU_DO_NOT_HAVE_AN_ACCEPTED_CONNECTION',
  CANNOT_DISCONNECT_CONNECTION_REQUEST_NOT_ACCEPTED:
    'CANNOT_DISCONNECT_CONNECTION_REQUEST_NOT_ACCEPTED',
} as const;
