/**
 * 1000 ~ 1999
 */
export const USER_ERROR_CODE = {
  ALREADY_CREATED_USER: 1000,
  INVALID_EMAIL_VERIFY_TOKEN: 1001,
  ALREADY_VERIFIED_EMAIL: 1002,
  CANNOT_RESEND_VERIFICATION_EMAIL_AN_HOUR: 1003,
  ALREADY_USED_EMAIL_VERIFY_TOKEN: 1004,
  CANNOT_RESEND_PASSWORD_CHANGE_VERIFICATION_EMAIL_AN_HOUR: 1005,
  INVALID_PASSWORD_CHANGE_VERIFY_TOKEN: 1006,
  ALREADY_USED_PASSWORD_CHANGE_VERIFY_TOKEN: 1007,
} as const;
