const SERVER = {
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
  DOMAIN: 'DOMAIN',
} as const;

const AUTH = {
  HASH_ROUND: 'HASH_ROUND',
} as const;

const JWT = {
  JWT_SECRET: 'JWT_SECRET',
  JWT_ACCESS_TOKEN_EXPIRES_IN: 'JWT_ACCESS_TOKEN_EXPIRES_IN',
  JWT_REFRESH_TOKEN_EXPIRES_IN: 'JWT_REFRESH_TOKEN_EXPIRES_IN',
} as const;

const EMAIL = {
  EMAIL_HOST: 'EMAIL_HOST',
  EMAIL_PORT: 'EMAIL_PORT',
  EMAIL_AUTH_USER: 'EMAIL_AUTH_USER',
  EMAIL_AUTH_PASSWORD: 'EMAIL_AUTH_PASSWORD',
} as const;

const DATABASE = {
  DATABASE_URL: 'DATABASE_URL',
} as const;

const AWS = {
  CLOUDWATCH_AWS_ACCESS_KEY_ID: 'CLOUDWATCH_AWS_ACCESS_KEY_ID',
  CLOUDWATCH_AWS_SECRET_ACCESS_KEY: 'CLOUDWATCH_AWS_SECRET_ACCESS_KEY',
  CLOUDWATCH_AWS_REGION: 'CLOUDWATCH_AWS_REGION',
  CLOUDWATCH_AWS_LOG_GROUP_NAME: 'CLOUDWATCH_AWS_LOG_GROUP_NAME',
  CLOUDWATCH_AWS_LOG_STREAM_NAME: 'CLOUDWATCH_AWS_LOG_STREAM_NAME',

  AWS_S3_ACCESS_KEY: 'AWS_S3_ACCESS_KEY',
  AWS_S3_SECRET_KEY: 'AWS_S3_SECRET_KEY',
  AWS_S3_REGION: 'AWS_S3_REGION',
  AWS_S3_BUCKET: 'AWS_S3_BUCKET',
  AWS_S3_BUCKET_URL: 'AWS_S3_BUCKET_URL',
} as const;

const USER = {
  USER_ATTACHMENT_URL: 'USER_ATTACHMENT_URL',
  USER_DEFAULT_PROFILE_IMAGE_PATH: 'USER_DEFAULT_PROFILE_IMAGE_PATH',
} as const;

const BLOG = {
  BLOG_ATTACHMENT_URL: 'BLOG_ATTACHMENT_URL',
} as const;

const BLOG_POST = {
  BLOG_POST_ATTACHMENT_URL: 'BLOG_POST_ATTACHMENT_URL',
} as const;

const ATTACHMENT = {
  ATTACHMENT_URL: 'ATTACHMENT_URL',
} as const;

/**
 * 각 주제에 맞게 묶어서 export 하지 않는 변수로 생성하고
 * ENV_KEY 객체에 spread
 */
export const ENV_KEY = {
  ...SERVER,
  ...AUTH,
  ...JWT,
  ...EMAIL,
  ...DATABASE,
  ...AWS,
  ...USER,
  ...BLOG,
  ...BLOG_POST,
  ...ATTACHMENT,
} as const;
