name: app-dev

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image (development)
        run: |
          docker build --platform linux/amd64 -f Dockerfile.dev -t nicodora/honey-moa-dev:latest .

      - name: Push Docker image
        run: |
          docker push nicodora/honey-moa-dev:latest

      # 배포 단계: EC2에 SSH로 접속하여 컨테이너 업데이트
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 기존 컨테이너 중지 및 삭제
            sudo docker-compose -f docker-compose.dev.yaml down

            # 오래된 이미지 정리
            sudo docker rmi -f nicodora/honey-moa-dev:latest || true

            # 최신 이미지 pull
            sudo docker pull nicodora/honey-moa-dev:latest

            # 최신 이미지로 Docker Compose 실행
            sudo docker-compose -f docker-compose.dev.yaml up -d
